### PR TITLE
Upgraded ajv to 5.5.2 and mime-db to 1.32.0

### PR DESCRIPTION
**Pull request by jannik-kraemer**
I have added ajv@5.5.2 and mime-db@1.32.0

### CODE REVIEW

**Comment by andrew** [comment]
@TheCookieJK we don't need them added to package.json, just the yarn.lock file updated

**Comment by jannik-kraemer** [comment]
Ok I used the yarn add command and it did this automaticly

**Comment by jannik-kraemer** [comment]
Sry for the mess. I'am new on GitHub.

**Comment by andrew** [comment]
Not a problem, thanks for tackling it!

**Pull request merged**
